services:
 
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    profiles: [infra]
    ports:
      - 5434:5432
    volumes:
      - ../../.data/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=basket
    networks:
      - payment-plateform-network

  postgres-test:
    image: postgres:16-alpine
    container_name: postgres-test
    profiles: [test]
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=basket-test
    networks:
      - payment-plateform-network

networks:
  payment-plateform-network:
    driver: bridge
    name: payment-plateform-network
